version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3001:3001"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
